# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170113_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
